### PR TITLE
needed to replace the "::" values with "-" because of an issue with u…

### PR DESCRIPTION
**Pull request by MacGregor001**
…pdated xml standards... at least in the eyes of the ReXML used in updated Ruby Interpreters in Puppet Agents.

### CODE REVIEW

**Comment by Areson** [comment]
@MacGregor001 Nice to see you! I was a bit behind merging some pull requests for some other compatibility issues, so I had to make a slight change to get this merged in. Can you take a look at the resulting changes I merged back and and verify that everything is working as expected? If it all looks good I'll get this merged and see if I can update the package on the forge.

**Comment by Areson** [comment]
You may need to merge changes in master back into your pull request as I've committed a few adjustments since yesterday based on some other pull requests.

**Comment by MacGregor001** [comment]
Neat - This is my first experience with GitHub and other's repos... gonna see what I can learn here... can't be that different from M$ Git stuff. :-)

**Comment by Areson** [comment]
Bump @MacGregor001

**Pull request merged**
